dataset: breast

data_path: "D:/hcmus/s8/kltn/icmr/ICMR Datasets/Breast_GSE45827.csv"
labels_path: null
merge_col: null
label_col: "type"
sample_col: "samples"

n_clusters: 6
class_labels: ["basal", "HER", "luminal_A", "luminal_B", "cell_line", "normal"]
random_state: 42

n_select_features: 1000

umap_n_neighbors: 15
umap_min_dist: 0.1

dbscan_eps: 15.0
dbscan_min_samples: 3
